DealerCenter/Controllers/PurchaseManagerOrderController.cs
using DealerCenter.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace DealerCenter.Controllers
{
    public class PurchaseManagerOrderController : Controller
    {
        DealerCenterContext db;

        public PurchaseManagerOrderController(DealerCenterContext context)
        {
            db = context;
        }

        public IActionResult PurchaseManagerOrders()
        {
            IQueryable<Order> order = db.Orders.Where(o => o.PurchaseManager.Login == User.Identity.Name ||
                                                o.SalesManager.Login == User.Identity.Name ||
                                                User.HasClaim(ClaimsIdentity.DefaultRoleClaimType, RoleEnum.Администратор.ToString()))
                                               .Where(o => o.PaymentStatusId == (int)PaymentStatusEnum.ОжиданиеПолнойОплаты)
                                               .Include(o => o.Client)
                                               .Include(o => o.PurchaseManager)
                                               .Include(o => o.SalesManager)
                                               .Include(o => o.Machinery)
                                               .Include(o => o.Machinery.MachineryClass)
                                               .Include(o => o.Machinery.Supplier)
                                               .Include(o => o.OrderStatus)
                                               .Include(o => o.PaymentStatus);
            return View(order.ToList());
        }

        [Authorize(Roles = "Администратор, ОтветственныйЗаЗакупку")]
        [HttpGet]
        [ActionName("ChangeOrderStatusToWaitingForDelivery")]
        public async Task<IActionResult> ConfirmChangeOrderStatusToWaitingForDelivery(int? id)
        {
            if (id != null)
            {
                Order order = await db.Orders.FirstOrDefaultAsync(p => p.Id == id);
                if (order != null)
                {
                    return View(order);
                }
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> ChangeOrderStatusToWaitingForDelivery(OrderSetDateViewModel orderModel)
        {
            Order order = db.Orders.Find(orderModel.Id);
            order.OrderStatus = db.OrderStatuses.Find((int)OrderStatusEnum.ОжиданиеДоставки);
            order.DeliveryDate = orderModel.DeliveryDate;
            db.Orders.Update(order);
            await db.SaveChangesAsync();
            return RedirectToAction("PurchaseManagerOrders");
        }

        [Authorize(Roles = "Администратор, ОтветственныйЗаЗакупку")]
        [HttpGet]
        [ActionName("ChangeOrderStatusToReadyToTransfer")]
        public async Task<IActionResult> ConfirmChangeOrderStatusToReadyToTransfer(int? id)
        {
            if (id != null)
            {
                Order order = await db.Orders.FirstOrDefaultAsync(p => p.Id == id);
                if (order != null)
                {
                    return View(order);
                }
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> ChangeOrderStatusToReadyToTransfer(OrderSetDateViewModel orderModel)
        {
            Order order = db.Orders.Find(orderModel.Id);
            order.OrderStatus = db.OrderStatuses.Find((int)OrderStatusEnum.ГотовКПередаче);
            order.DeliveryDate = DateTime.Now;
            db.Orders.Update(order);
            await db.SaveChangesAsync();
            return RedirectToAction("PurchaseManagerOrders");
        }

        [Authorize(Roles = "Администратор, ОтветственныйЗаЗакупку")]
        [HttpGet]
        [ActionName("Cancel")]
        public async Task<IActionResult> ConfirmCancel(int? id)
        {
            if (id != null)
            {
                Order order = await db.Orders.FirstOrDefaultAsync(p => p.Id == id);
                if (order != null)
                    return View(order);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Cancel(int? id)
        {
            if (id != null)
            {
                Order order = await db.Orders.FirstOrDefaultAsync(p => p.Id == id);
                if (order != null)
                {
                    order.ClosingDate = DateTime.Now;
                    order.PaymentStatus = db.PaymentStatuses.Find((int)PaymentStatusEnum.ЗаказОтменён);
                    order.OrderStatus = db.OrderStatuses.Find((int)OrderStatusEnum.ЗаказОтменён);
                    db.Orders.Update(order);
                    await db.SaveChangesAsync();
                    return RedirectToAction("PurchaseManagerOrders");
                }
            }
            return NotFound();
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id != null)
            {
                Order order = await db.Orders.Include(o => o.Client)
                                             .Include(o => o.SalesManager)
                                             .Include(o => o.PurchaseManager)
                                             .Include(o => o.OrderStatus)
                                             .Include(o => o.PaymentStatus)
                                             .Include(o => o.Machinery)
                                             .Include(o => o.Machinery.MachineryClass)
                                             .Include(o => o.Machinery.Supplier)
                                             .FirstOrDefaultAsync(p => p.Id == id);
                if (order != null)
                    return View(order);
            }
            return NotFound();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DealerCenter/Controllers/SalesManagerOrderController.cs
using DealerCenter.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace DealerCenter.Controllers
{
    public class SalesManagerOrderController : Controller
    {
        DealerCenterContext db;

        public SalesManagerOrderController(DealerCenterContext context)
        {
            db = context;
        }

        public ActionResult SalesManagerOrders()
        {
            IQueryable<Order> order = db.Orders.Where(o => o.SalesManager.Login == User.Identity.Name ||
                                                o.PurchaseManager.Login == User.Identity.Name ||
                                                User.HasClaim(ClaimsIdentity.DefaultRoleClaimType, RoleEnum.Администратор.ToString()))
                                               .Where(o => o.OrderStatusId == (int)OrderStatusEnum.ПроверкаДоступностиЗакупки ||
                                                o.OrderStatusId == (int)OrderStatusEnum.ГотовКПередаче)
                                               .Include(o => o.Client)
                                               .Include(o => o.PurchaseManager)
                                               .Include(o => o.SalesManager)
                                               .Include(o => o.Machinery)
                                               .Include(o => o.Machinery.MachineryClass)
                                               .Include(o => o.Machinery.Supplier)
                                               .Include(o => o.OrderStatus)
                                               .Include(o => o.PaymentStatus);
            return View(order.ToList());
        }

        [Authorize(Roles = "Администратор, Продавец")]
        public IActionResult Create(int? machineryClassId, int? supplierId)
        {
            IQueryable<Machinery> machineries = db.Machineries.Where(m => !m.isDeleted);

            List<MachineryClass> machineryClasses = db.MachineryClasses.ToList();
            machineryClasses.Insert(0, new MachineryClass { Id = 0, Name = "Все" });
            ViewBag.MachineryClasses = new SelectList(machineryClasses, "Id", "Name", machineryClassId);

            List<Supplier> suppliers = db.Suppliers.ToList();
            suppliers.Insert(0, new Supplier { Id = 0, Name = "Все" });
            ViewBag.Suppliers = new SelectList(suppliers, "Id", "Name", supplierId);

            if (machineryClassId != null && machineryClassId != 0)
            {
                machineries = machineries.Where(m => m.MachineryClassId == machineryClassId);
            }
            if (supplierId != null && supplierId != 0)
            {
                machineries = machineries.Where(m => m.SupplierId == supplierId);
            }
            
            ViewBag.SalesManagers = new SelectList(db.Employees.Where(x => x.Role.Name == RoleEnum.Продавец.ToString() && !x.isDeleted).ToList(), "Id", "Name");
            ViewBag.PurchaseManagers = new SelectList(db.Employees.Where(x => x.Role.Name == RoleEnum.ОтветственныйЗаЗакупку.ToString() && !x.isDeleted).ToList(), "Id", "Name");
            ViewBag.Machineries = new SelectList(machineries, "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(OrderCreateViewModel orderModel)
        {
            Order order = new Order();

            Client client = db.Clients.Where(c => c.Name == orderModel.ClientName && c.Passport == orderModel.ClientPassport).FirstOrDefault();
            if (client == null)
            {
                Client newClient = new Client { Name = orderModel.ClientName, Passport = orderModel.ClientPassport, PhoneNumber = orderModel.ClientPhoneNumber };
                db.Clients.Add(newClient);
                await db.SaveChangesAsync();
                client = db.Clients.Where(c => c.Name == orderModel.ClientName && c.Passport == orderModel.ClientPassport).FirstOrDefault();
            }
            order.ClientId = client.Id;
            order.SalesManagerId = orderModel.SalesManagerId;
            order.PurchaseManagerId = orderModel.PurchaseManagerId;
            order.MachineryId = orderModel.MachineryId;
            order.OrderStatus = db.OrderStatuses.Find((int)OrderStatusEnum.ПроверкаДоступностиЗакупки);
            order.PaymentStatus = db.PaymentStatuses.Find((int)PaymentStatusEnum.ОжиданиеПредоплаты);
            order.RegistrationDate = DateTime.Now;
            order.PurchasePrice = db.Machineries.Find(orderModel.MachineryId).PurchasePrice;
            order.SellingPrice = db.Machineries.Find(orderModel.MachineryId).SellingPrice;
            db.Orders.Add(order);
            await db.SaveChangesAsync();
            return RedirectToAction("SalesManagerOrders");
        }

        [Authorize(Roles = "Администратор, Продавец")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Order order = await db.Orders.FirstOrDefaultAsync(p => p.Id == id);
                if (order != null)
                {
                    ViewBag.Clients = new SelectList(db.Clients.ToList(), "Id", "Name");
                    ViewBag.SalesManagers = new SelectList(db.Employees.Where(x => x.Role.Name == RoleEnum.Продавец.ToString()).ToList(), "Id", "Name");
                    ViewBag.PurchaseManagers = new SelectList(db.Employees.Where(x => x.Role.Name == RoleEnum.ОтветственныйЗаЗакупку.ToString()).ToList(), "Id", "Name");
                    ViewBag.Machineries = new SelectList(db.Machineries.ToList(), "Id", "Model");
                    return View(order);
                }
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Order order)
        {
            db.Orders.Update(order);
            await db.SaveChangesAsync();
            return RedirectToAction("SalesManagerOrders");
        }

        [Authorize(Roles = "Администратор, Продавец")]
        [HttpGet]
        [ActionName("ChangePaymentStatusToAwaitingFullPayment")]
        public async Task<IActionResult> ConfirmChangePaymentStatusToAwaitingFullPayment(int? id)
        {
            if (id != null)
            {
                Order order = await db.Orders.FirstOrDefaultAsync(p => p.Id == id);
                if (order != null)
                {
                    return View(order);
                }
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> ChangePaymentStatusToAwaitingFullPayment(int? id)
        {
            Order order = db.Orders.Find(id);
            order.PaymentStatus = db.PaymentStatuses.Find((int)PaymentStatusEnum.ОжиданиеПолнойОплаты);
            db.Orders.Update(order);
            await db.SaveChangesAsync();
            return RedirectToAction("SalesManagerOrders");
        }

        [Authorize(Roles = "Администратор, Продавец")]
        [HttpGet]
        [ActionName("ChangePaymentStatusToFullyPaid")]
        public async Task<IActionResult> ConfirmChangePaymentStatusToFullyPaid(int? id)
        {
            if (id != null)
            {
                Order order = await db.Orders.FirstOrDefaultAsync(p => p.Id == id);
                if (order != null)
                {
                    return View(order);
                }
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> ChangePaymentStatusToFullyPaid(int? id)
        {
            Order order = db.Orders.Find(id);
            order.PaymentStatus = db.PaymentStatuses.Find((int)PaymentStatusEnum.ПолностьюОплачен);
            db.Orders.Update(order);
            await db.SaveChangesAsync();
            return RedirectToAction("SalesManagerOrders");
        }

        [Authorize(Roles = "Администратор, Продавец")]
        [HttpGet]
        [ActionName("Close")]
        public async Task<IActionResult> ConfirmClose(int? id)
        {
            if (id != null)
            {
                Order order = await db.Orders.FirstOrDefaultAsync(p => p.Id == id);
                if (order != null)
                {
                    return View(order);
                }
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Close(int? id)
        {
            Order order = db.Orders.Find(id);
            order.OrderStatus = db.OrderStatuses.Find((int)OrderStatusEnum.ЗаказЗакрыт);
            order.ClosingDate = DateTime.Now;
            db.Orders.Update(order);
            await db.SaveChangesAsync();
            return RedirectToAction("SalesManagerOrders");
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id != null)
            {
                Order order = await db.Orders.Include(o => o.Client)
                                             .Include(o => o.SalesManager)
                                             .Include(o => o.PurchaseManager)
                                             .Include(o => o.OrderStatus)
                                             .Include(o => o.PaymentStatus)
                                             .Include(o => o.Machinery)
                                             .Include(o => o.Machinery.MachineryClass)
                                             .Include(o => o.Machinery.Supplier)
                                             .FirstOrDefaultAsync(p => p.Id == id);
                if (order != null)
                    return View(order);
            }
            return NotFound();
        }

        [Authorize(Roles = "Администратор, Продавец")]
        [HttpGet]
        [ActionName("Delete")]

DealerCenter/Views/PurchaseManagerOrder/Cancel.cshtml
@model DealerCenter.Models.Order
@{
    ViewBag.Title = "Отмена заказ";
}

<div>
    <dl class="dl-horizontal">
        <dt>Вы уверены, что хотите отменить заказ №@Model.Id ?</dt>
    </dl>

    <div>
        <form asp-controller="Order" asp-action="Cancel" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Отмена" />
            </div>
        </form>
    </div>
</div>

DealerCenter/Views/PurchaseManagerOrder/ChangeOrderStatusToReadyToTransfer.cshtml
@model DealerCenter.Models.Order
@{
    ViewBag.Title = "Изменение статуса заказа";
}

<div>
    <dl class="dl-horizontal">
        <dt>Подтвердите прибытие заказа.</dt>
    </dl>

    <div>
        <form asp-controller="PurchaseManagerOrder" asp-action="ChangeOrderStatusToReadyToTransfer" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Подтвердить" />
            </div>
        </form>
    </div>
</div>

DealerCenter/Views/PurchaseManagerOrder/ChangeOrderStatusToWaitingForDelivery.cshtml
@model DealerCenter.Models.Order
@{
    ViewBag.Title = "Изменение статуса заказа";
}

<div>
    <dl class="dl-horizontal">
        <dt>Введите ожидаемую дату поставки.</dt>
    </dl>

    <div>
        <form asp-controller="PurchaseManagerOrder" asp-action="ChangeOrderStatusToWaitingForDelivery" method="post">
            <div class="form-group">
                <label asp-for="DeliveryDate" class="control-label">Дата доставки</label>
                <input type ="datetime-local" min="@DateTime.Now" value="@DateTime.Now" asp-for= "DeliveryDate" class="form-control">
            </div>
            
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Подтвердить" />
            </div>
        </form>
    </div>
</div>

DealerCenter/Views/PurchaseManagerOrder/Edit.cshtml
@model DealerCenter.Models.Order
@{
    ViewBag.Title = "Редактировать заказ";
}

<form asp-action="edit" asp-controller="Order" asp-route-id="@Model.Id">
    <div class="form-group">
        <label asp-for="ClientId" class="control-label">Клиент</label>
        <select asp-for="ClientId" asp-items="ViewBag.Clients" class="form-control"></select>
    </div>

    <div class="form-group">
        <label asp-for="SalesManagerId" class="control-label">Продавец</label>
        <select asp-for="SalesManagerId" asp-items="ViewBag.SalesManagers" class="form-control"></select>
    </div>

    <div class="form-group">
        <label asp-for="PurchaseManagerId" class="control-label">Ответственный за закупку</label>
        <select asp-for="PurchaseManagerId" asp-items="ViewBag.PurchaseManagers" class="form-control"></select>
    </div>

    <div class="form-group">
        <label asp-for="MachineryId" class="control-label">Состав заказа</label>
        <select asp-for="MachineryId" asp-items="ViewBag.Machineries" class="form-control"></select>
    </div>

    <div class="form-group">
        <input type="submit" value="Сохранить изменения" class="btn btn-default" />
    </div>
</form>

DealerCenter/Views/PurchaseManagerOrder/PurchaseManagerOrders.cshtml
@model IEnumerable<DealerCenter.Models.Order>
@{
    ViewData["Title"] = "Список заказов";
}

<!DOCTYPE html>

<html>
<head>
    <title>Заказы</title>
</head>

<body>
    <h3>Активные заказы</h3>
    <h4>Ожидают подтверждения</h4>
    <table class="table table-striped">
        <tr>
            <td>Id</td>
            <td>Клиент</td>
            <td>Продавец</td>
            <td>Состав заказа</td>
            <td>Дата оформления</td>
            <td>Действия</td>
            <td></td>
            <td></td>
        </tr>
        @foreach (var order in Model.Where(o => o.OrderStatusId == (int)OrderStatusEnum.ПроверкаДоступностиЗакупки))
        {
    <tr>
        <td>@order.Id</td>
        <td>@order.Client.Name</td>
        <td>@order.SalesManager.Name</td>
        <td>@order.Machinery.Name</td>
        <td>@order.RegistrationDate</td>
        <td>
            <a asp-action="Details" asp-controller="SalesManagerOrder" asp-route-id="@order.Id">Подробнее</a>
        </td>
        @if (User.IsInRole(RoleEnum.Администратор.ToString()) || User.IsInRole(RoleEnum.ОтветственныйЗаЗакупку.ToString()))
        {
        <td>
            <a asp-action="ChangeOrderStatusToWaitingForDelivery" asp-controller="PurchaseManagerOrder" asp-route-id="@order.Id">Подтвердить закупку</a>
        </td>
        <td>
            <a asp-action="Cancel" asp-controller="PurchaseManagerOrder" asp-route-id="@order.Id">Отменить</a>
        </td>
        }
    </tr>
        }
    </table>
    <h4>Ожидают прибытия</h4>
    <table class="table table-striped">
        <tr>
            <td>Id</td>
            <td>Клиент</td>
            <td>Продавец</td>
            <td>Состав заказа</td>
            <td>Дата оформления</td>
            <td>Действия</td>
            <td></td>
            <td></td>
        </tr>
        @foreach (var order in Model.Where(o => o.OrderStatusId == (int)OrderStatusEnum.ОжиданиеДоставки))
        {
    <tr>
        <td>@order.Id</td>
        <td>@order.Client.Name</td>
        <td>@order.SalesManager.Name</td>
        <td>@order.Machinery.Name</td>
        <td>@order.RegistrationDate</td>
        <td>
            <a asp-action="Details" asp-controller="SalesManagerOrder" asp-route-id="@order.Id">Подробнее</a>
        </td>
        @if (User.IsInRole(RoleEnum.Администратор.ToString()) || User.IsInRole(RoleEnum.ОтветственныйЗаЗакупку.ToString()))
        {
        <td>
            <a asp-action="ChangeOrderStatusToReadyToTransfer" asp-controller="PurchaseManagerOrder" asp-route-id="@order.Id">Подтвердить прибытие</a>
        </td>
        }
    </tr>
        }
    </table>
</body>
</html>