DealerCenter/Models/Supplier.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DealerCenter.Models
{
    public class Supplier
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public bool isDeleted { get; set; }
        //=====================================
        public List<Machinery> Machineries { get; set; }

        public Supplier()
        {
            Machineries = new List<Machinery>();
        }
    }
}

DealerCenter/Controllers/MachineryController.cs
using DealerCenter.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DealerCenter.Controllers
{
    public class MachineryController : Controller
    {
        DealerCenterContext db;

        public MachineryController(DealerCenterContext context)
        {
            db = context;
        }

        public IActionResult Machineries(int? machineryClassId, int? supplierId)
        {
            IQueryable<Machinery> machineries = db.Machineries.Include(m => m.Supplier)
                                                              .Include(m => m.MachineryClass);

            List<MachineryClass> machineryClasses = db.MachineryClasses.ToList();
            machineryClasses.Insert(0, new MachineryClass { Id = 0, Name = "Все" });
            ViewBag.MachineryClasses = new SelectList(machineryClasses, "Id", "Name", machineryClassId);

            List<Supplier> suppliers = db.Suppliers.ToList();
            suppliers.Insert(0, new Supplier { Id = 0, Name = "Все" });
            ViewBag.Suppliers = new SelectList(suppliers, "Id", "Name", supplierId);

            if (machineryClassId != null && machineryClassId != 0)
            {
                machineries = machineries.Where(m => m.MachineryClassId == machineryClassId);
            }
            if (supplierId != null && supplierId != 0)
            {
                machineries = machineries.Where(m => m.SupplierId == supplierId);
            }
            return View(machineries.ToList());
        }

        [Authorize(Roles = "Администратор, ОтветственныйЗаЗакупку")]
        public IActionResult Create()
        {
            ViewBag.Suppliers = new SelectList(db.Suppliers.ToList(), "Id", "Name");
            ViewBag.Classes = new SelectList(db.MachineryClasses.ToList(), "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Machinery machinery)
        {
            db.Machineries.Add(machinery);
            await db.SaveChangesAsync();
            return RedirectToAction("Machineries");
        }

        [Authorize(Roles = "Администратор, ОтветственныйЗаЗакупку")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Machinery machinery = await db.Machineries.Include(m => m.MachineryClass).FirstOrDefaultAsync(p => p.Id == id);
                if (machinery != null)
                {
                    ViewBag.Suppliers = new SelectList(db.Suppliers.ToList(), "Id", "Name");
                    ViewBag.Classes = new SelectList(db.MachineryClasses.ToList(), "Id", "Name");
                    return View(machinery);
                }
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Machinery machinery)
        {
            db.Machineries.Update(machinery);
            await db.SaveChangesAsync();
            return RedirectToAction("Machineries");
        }

        [Authorize(Roles = "Администратор, ОтветственныйЗаЗакупку")]
        [HttpGet]
        [ActionName("FlagDelete")]
        public async Task<IActionResult> ConfirmFlagDelete(int? id)
        {
            if (id != null)
            {
                Machinery machinery = await db.Machineries.FirstOrDefaultAsync(p => p.Id == id);
                if (machinery != null)
                    return View(machinery);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> FlagDelete(int? id)
        {
            if (id != null)
            {
                Machinery machinery = await db.Machineries.FirstOrDefaultAsync(p => p.Id == id);
                if (machinery != null)
                {
                    machinery.isDeleted = true;
                    db.Machineries.Update(machinery);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Machineries");
                }
            }
            return NotFound();
        }

        [Authorize(Roles = "Администратор, ОтветственныйЗаЗакупку")]
        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Machinery machinery = await db.Machineries.FirstOrDefaultAsync(p => p.Id == id);
                if (machinery != null)
                    return View(machinery);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                Machinery machinery = await db.Machineries.FirstOrDefaultAsync(p => p.Id == id);
                if (machinery != null)
                {
                    db.Machineries.Remove(machinery);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Machineries");
                }
            }
            return NotFound();
        }

        [Authorize(Roles = "Администратор, ОтветственныйЗаЗакупку")]
        [HttpGet]
        [ActionName("Restore")]
        public async Task<IActionResult> ConfirmRestore(int? id)
        {
            if (id != null)
            {
                Machinery machinery = await db.Machineries.FirstOrDefaultAsync(p => p.Id == id);
                if (machinery != null)
                    return View(machinery);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Restore(int? id)
        {
            if (id != null)
            {
                Machinery machinery = await db.Machineries.FirstOrDefaultAsync(p => p.Id == id);
                if (machinery != null)
                {
                    machinery.isDeleted = false;
                    db.Machineries.Update(machinery);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Machineries");
                }
            }
            return NotFound();
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id != null)
            {
                List<Order> orders = await db.Orders.Include(o => o.Client)
                                                    .Include(o => o.SalesManager)
                                                    .Include(o => o.PurchaseManager)
                                                    .Include(o => o.OrderStatus)
                                                    .Include(o => o.PaymentStatus)
                                                    .Include(o => o.Machinery)
                                                    .Include(o => o.Machinery.MachineryClass)
                                                    .Include(o => o.Machinery.Supplier)
                                                    .Where(o => o.MachineryId == id)
                                                    .ToListAsync();
                if (orders != null)
                    return View(orders);
            }
            return NotFound();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DealerCenter/Controllers/SupplierController.cs
using DealerCenter.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DealerCenter.Controllers
{
    public class SupplierController : Controller
    {
        DealerCenterContext db;

        public SupplierController(DealerCenterContext context)
        {
            db = context;
        }
        
        public IActionResult Suppliers()
        {
            IQueryable<Supplier> supplier = db.Suppliers.Include(s => s.Machineries);
            return View(supplier.ToList());
        }

        [Authorize(Roles = "Администратор, ОтветственныйЗаЗакупку")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Supplier supplier)
        {
            db.Suppliers.Add(supplier);
            await db.SaveChangesAsync();
            return RedirectToAction("Suppliers");
        }

        [Authorize(Roles = "Администратор, ОтветственныйЗаЗакупку")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Supplier supplier = await db.Suppliers.FirstOrDefaultAsync(p => p.Id == id);
                if (supplier != null)
                {
                    return View(supplier);
                }
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Supplier supplier)
        {
            db.Suppliers.Update(supplier);
            await db.SaveChangesAsync();
            return RedirectToAction("Suppliers");
        }


        [Authorize(Roles = "Администратор, ОтветственныйЗаЗакупку")]
        [HttpGet]
        [ActionName("FlagDelete")]
        public async Task<IActionResult> ConfirmFlagDelete(int? id)
        {
            if (id != null)
            {
                Supplier supplier = await db.Suppliers.FirstOrDefaultAsync(p => p.Id == id);
                if (supplier != null)
                    return View(supplier);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> FlagDelete(int? id)
        {
            if (id != null)
            {
                Supplier supplier = await db.Suppliers.Include(s => s.Machineries).FirstOrDefaultAsync(p => p.Id == id);
                if (supplier != null)
                {
                    supplier.isDeleted = true;
                    db.Suppliers.Update(supplier);
                    await db.SaveChangesAsync();
                    foreach(var machinery in supplier.Machineries)
                    {
                        machinery.isDeleted = true;
                        await db.SaveChangesAsync();
                    }
                    return RedirectToAction("Suppliers");
                }
            }
            return NotFound();
        }

        [Authorize(Roles = "Администратор, ОтветственныйЗаЗакупку")]
        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Supplier supplier = await db.Suppliers.FirstOrDefaultAsync(p => p.Id == id);
                if (supplier != null)
                    return View(supplier);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                Supplier suppliers = await db.Suppliers.FirstOrDefaultAsync(p => p.Id == id);
                if (suppliers != null)
                {
                    db.Suppliers.Remove(suppliers);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Suppliers");
                }
            }
            return NotFound();
        }

        [Authorize(Roles = "Администратор, ОтветственныйЗаЗакупку")]
        [HttpGet]
        [ActionName("Restore")]
        public async Task<IActionResult> ConfirmRestore(int? id)
        {
            if (id != null)
            {
                Supplier supplier = await db.Suppliers.FirstOrDefaultAsync(p => p.Id == id);
                if (supplier != null)
                    return View(supplier);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Restore(int? id)
        {
            if (id != null)
            {
                Supplier supplier = await db.Suppliers.FirstOrDefaultAsync(p => p.Id == id);
                if (supplier != null)
                {
                    supplier.isDeleted = false;
                    db.Suppliers.Update(supplier);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Suppliers");
                }
            }
            return NotFound();
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id != null)
            {
                List<Machinery> machineries = await db.Machineries.Include(m => m.Supplier)
                                                                  .Include(m => m.MachineryClass)
                                                                  .Where(m => m.SupplierId == id)
                                                                  .ToListAsync();
                if (machineries != null)
                    return View(machineries);
            }
            return NotFound();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DealerCenter/Views/Supplier/Create.cshtml
@model DealerCenter.Models.Supplier

@{
    ViewBag.Title = "Добавить поставщика";
}

<form asp-action="Create" asp-controller="Supplier">
    <div class="form-group">
        <label asp-for="Name" class="control-label">Имя поставщика</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="PhoneNumber" class="control-label">Номер телефона</label>
        <input type="text" asp-for="PhoneNumber" class="form-control" />
    </div>

    <div class="form-group">
        <input type="submit" value="Добавить поставщика" class="btn btn-default" />
    </div>
</form>

DealerCenter/Views/Supplier/Delete.cshtml
@model DealerCenter.Models.Supplier
@{
    ViewBag.Title = "Удаление поставщика";
}

<div>
    <dl class="dl-horizontal">
        <dt>Вы уверены, что хотите удалить поставщика "@Model.Name" ?</dt>
    </dl>

    <div>
        <form asp-controller="Supplier" asp-action="Delete" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Удалить" />
            </div>
        </form>
    </div>
</div>

DealerCenter/Views/Supplier/Details.cshtml
@model IEnumerable<DealerCenter.Models.Machinery>
@{
    ViewData["Title"] = "Список заказов клиента";
}

<!DOCTYPE html>

<html>
<head>
    <title>Модели спецтехники поставщика @Model.FirstOrDefault().Supplier.Name</title>
</head>

<body>
    <h3>Модели спецтехники от @Model.FirstOrDefault().Supplier.Name</h3>
    <h4>Доступные модели</h4>
    <table class="table table-striped">
        <tr>
            <td>Наименование</td>
            <td>Класс</td>
            <td>Год выпуска</td>
            <td>Цена закупки (руб.)</td>
            <td>Цена продажи (руб.)</td>
            <td>Действия</td>
        </tr>
        @foreach (var machinery in Model.Where(m => !m.isDeleted))
        {
            <tr>
                <td>@machinery.Name</td>
                <td>@machinery.MachineryClass.Name</td>
                <td>@machinery.YearOfManufacture</td>
                <td>@machinery.PurchasePrice</td>
                <td>@machinery.SellingPrice</td>
                <td>
                    <a asp-action="Details" asp-controller="Machinery" asp-route-id="@machinery.Id">Подробнее</a>
                </td>
            </tr>
        }
    </table>
    <h4>Удалённые модели</h4>
    <table class="table table-striped">
        <tr>
            <td>Наименование</td>
            <td>Класс</td>
            <td>Год выпуска</td>
            <td>Цена закупки (руб.)</td>
            <td>Цена продажи (руб.)</td>
            <td>Действия</td>
        </tr>
        @foreach (var machinery in Model.Where(m => m.isDeleted))
        {
            <tr>
                <td>@machinery.Name</td>
                <td>@machinery.MachineryClass.Name</td>
                <td>@machinery.YearOfManufacture</td>
                <td>@machinery.PurchasePrice</td>
                <td>@machinery.SellingPrice</td>
                <td>
                    <a asp-action="Details" asp-controller="Machinery" asp-route-id="@machinery.Id">Подробнее</a>
                </td>
            </tr>
        }
    </table>
</body>
</html>

DealerCenter/Views/Supplier/Edit.cshtml
@model DealerCenter.Models.Supplier
@{
    ViewBag.Title = "Редактировать поставщика";
}

<form asp-action="edit" asp-controller="Supplier" asp-route-id="@Model.Id">
    <div class="form-group">
        <label asp-for="Name" class="control-label">Имя поставщика</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="PhoneNumber" class="control-label">Номер телефона</label>
        <input type="text" asp-for="PhoneNumber" class="form-control" />
    </div>

    <div class="form-group">
        <input type="submit" value="Сохранить изменения" class="btn btn-default" />
    </div>
</form>

DealerCenter/Views/Supplier/FlagDelete.cshtml
@model DealerCenter.Models.Supplier
@{
    ViewBag.Title = "Удаление поставщика";
}

<div>
    <dl class="dl-horizontal">
        <dt>Вы уверены, что хотите удалить поставщика "@Model.Name" ?</dt>
    </dl>

    <div>
        <form asp-controller="Supplier" asp-action="FlagDelete" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Удалить" />
            </div>
        </form>
    </div>
</div>

DealerCenter/Views/Supplier/Restore.cshtml
@model DealerCenter.Models.Supplier
@{
    ViewBag.Title = "Восстановление поставщика";
}

<div>
    <dl class="dl-horizontal">
        <dt>Вы уверены, что хотите восстановить поставщика "@Model.Name" ?</dt>
    </dl>

    <div>
        <form asp-controller="Supplier" asp-action="Restore" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Восстановить" />
            </div>
        </form>
    </div>
</div>

DealerCenter/Views/Supplier/Suppliers.cshtml
@model IEnumerable<DealerCenter.Models.Supplier>
@{
    ViewData["Title"] = "Список поставщиков";
}

<!DOCTYPE html>

<html>
<head>
    <title>Поставщики</title>
</head>

<body>
    @if (User.IsInRole(RoleEnum.Администратор.ToString()) || User.IsInRole(RoleEnum.ОтветственныйЗаЗакупку.ToString()))
    {
        <a asp-action="Create">Добавить поставщика</a>
    }
        <h3>Поставщики</h3>
        <h4>Действующие поставщики</h4>
        <table class="table table-striped">
            <tr>
                <td>Имя</td>
                <td>Телефон</td>
                <td>Действия</td>
                <td></td>
                <td></td>
            </tr>
            @foreach (var supplier in Model.Where(e => !e.isDeleted))
            {
        <tr>
            <td>@supplier.Name</td>
            <td>@supplier.PhoneNumber</td>
            <td>
                <a asp-action="Details" asp-controller="Supplier" asp-route-id="@supplier.Id">Подробнее</a>
            </td>
            @if (User.IsInRole(RoleEnum.Администратор.ToString()) || User.IsInRole(RoleEnum.ОтветственныйЗаЗакупку.ToString()))
            {
                <td>
                    <a asp-action="Edit" asp-controller="Supplier" asp-route-id="@supplier.Id">Редактировать</a>
                </td>
                @if (supplier.Machineries.Count == 0)
                {
                    <td>
                        <a asp-action="Delete" asp-controller="Supplier" asp-route-id="@supplier.Id">Удалить</a>
                    </td>
                }
                else
                {
                    <td>
                        <a asp-action="FlagDelete" asp-controller="Supplier" asp-route-id="@supplier.Id">Удалить</a>
                    </td>
                }
            }
            else
            {
                <td></td>
                <td></td>
            }
        </tr>
            }
        </table>
        @if (Model.Where(e => e.isDeleted).Count() != 0)
        {
            <h4>Удалённые поставщики</h4>
            <table class="table table-striped">
                <tr>
                    <td>Имя</td>
                    <td>Телефон</td>
                    <td>Действия</td>
                    <td></td>
                </tr>
                @foreach (var supplier in Model.Where(e => e.isDeleted))
                {
            <tr>
                <td>@supplier.Name</td>
                <td>@supplier.PhoneNumber</td>
                <td>
                    <a asp-action="Details" asp-controller="Supplier" asp-route-id="@supplier.Id">Подробнее</a>
                </td>
                @if (User.IsInRole(RoleEnum.Администратор.ToString()) || User.IsInRole(RoleEnum.ОтветственныйЗаЗакупку.ToString()))
                {
                    <td>
                        <a asp-action="Restore" asp-controller="Supplier" asp-route-id="@supplier.Id">Восстановить</a>
                    </td>
                }
                else
                {
                    <td></td>
                }
            </tr>
                }
            </table>
        }
    </body>
</html>