DealerCenter/Controllers/ClientController.cs
using DealerCenter.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DealerCenter.Controllers
{
    public class ClientController : Controller
    {
        DealerCenterContext db;

        public ClientController(DealerCenterContext context)
        {
            db = context;
        }

        public IActionResult Clients()
        {
            IQueryable<Client> clients = db.Clients.Include(c => c.Orders);
            return View(clients.ToList());
        }

        [Authorize(Roles = "Администратор, Продавец")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Client client)
        {
            db.Clients.Add(client);
            await db.SaveChangesAsync();
            return RedirectToAction("Clients");
        }

        [Authorize(Roles = "Администратор, Продавец")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Client client = await db.Clients.FirstOrDefaultAsync(p => p.Id == id);
                if (client != null)
                {
                    return View(client);
                }
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Client client)
        {
            db.Clients.Update(client);
            await db.SaveChangesAsync();
            return RedirectToAction("Clients");
        }

        [Authorize(Roles = "Администратор, Продавец")]
        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Client client = await db.Clients.FirstOrDefaultAsync(p => p.Id == id);
                if (client != null)
                    return View(client);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                Client client = await db.Clients.FirstOrDefaultAsync(p => p.Id == id);
                if (client != null)
                {
                    db.Clients.Remove(client);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Clients");
                }
            }
            return NotFound();
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id != null)
            {
                List<Order> orders = await db.Orders.Include(o => o.Client)
                                                    .Include(o => o.SalesManager)
                                                    .Include(o => o.PurchaseManager)
                                                    .Include(o => o.OrderStatus)
                                                    .Include(o => o.PaymentStatus)
                                                    .Include(o => o.Machinery)
                                                    .Include(o => o.Machinery.MachineryClass)
                                                    .Include(o => o.Machinery.Supplier)
                                                    .Where(o => o.ClientId == id)
                                                    .ToListAsync();
                if (orders != null)
                    return View(orders);
            }
            return NotFound();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DealerCenter/Controllers/EmployeeController.cs
using DealerCenter.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DealerCenter.Controllers
{
    public class EmployeeController : Controller
    {
        DealerCenterContext db;

        public EmployeeController(DealerCenterContext context)
        {
            db = context;
        }

        [Authorize(Roles = "Администратор")]
        public IActionResult Employees()
        {
            IQueryable<Employee> employees = db.Employees.Include(e => e.Role);
            return View(employees.ToList());
        }

        [Authorize(Roles = "Администратор")]
        public IActionResult Create()
        {
            ViewBag.Roles = new SelectList(db.Roles.Where(r => r.Name != RoleEnum.Администратор.ToString()), "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Employee employee)
        {
            db.Employees.Add(employee);
            await db.SaveChangesAsync();
            return RedirectToAction("Employees");
        }

        [Authorize(Roles = "Администратор")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Employee employee = await db.Employees.Include(e => e.Role).FirstOrDefaultAsync(p => p.Id == id);
                if (employee != null)
                {
                    if (employee.Role.Name == RoleEnum.Администратор.ToString())
                    {
                        ViewBag.Roles = new SelectList(db.Roles.Where(r => r.Name == RoleEnum.Администратор.ToString()), "Id", "Name");
                    }
                    else
                    {
                        ViewBag.Roles = new SelectList(db.Roles.Where(r => r.Name != RoleEnum.Администратор.ToString()), "Id", "Name");
                    }
                    return View(employee);
                }
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Employee employee)
        {
            db.Employees.Update(employee);
            await db.SaveChangesAsync();
            return RedirectToAction("Employees");
        }

        [Authorize(Roles = "Администратор")]
        [HttpGet]
        [ActionName("FlagDelete")]
        public async Task<IActionResult> ConfirmFlagDelete(int? id)
        {
            if (id != null)
            {
                Employee employee = await db.Employees.FirstOrDefaultAsync(p => p.Id == id);
                if (employee != null)
                    return View(employee);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> FlagDelete(int? id)
        {
            if (id != null)
            {
                Employee employee = await db.Employees.FirstOrDefaultAsync(p => p.Id == id);
                if (employee != null)
                {
                    employee.isDeleted = true;
                    db.Employees.Update(employee);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Employees");
                }
            }
            return NotFound();
        }

        [Authorize(Roles = "Администратор")]
        [HttpGet]
        [ActionName("Restore")]
        public async Task<IActionResult> ConfirmRestore(int? id)
        {
            if (id != null)
            {
                Employee employee = await db.Employees.FirstOrDefaultAsync(p => p.Id == id);
                if (employee != null)
                    return View(employee);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Restore(int? id)
        {
            if (id != null)
            {
                Employee employee = await db.Employees.FirstOrDefaultAsync(p => p.Id == id);
                if (employee != null)
                {
                    employee.isDeleted = false;
                    db.Employees.Update(employee);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Employees");
                }
            }
            return NotFound();
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id != null)
            {
                List<Order> orders = await db.Orders.Include(o => o.Client)
                                                    .Include(o => o.SalesManager)
                                                    .Include(o => o.PurchaseManager)
                                                    .Include(o => o.OrderStatus)
                                                    .Include(o => o.PaymentStatus)
                                                    .Include(o => o.Machinery)
                                                    .Include(o => o.Machinery.MachineryClass)
                                                    .Include(o => o.Machinery.Supplier)
                                                    .Where(o => o.SalesManagerId == id || o.PurchaseManagerId == id)
                                                    .ToListAsync();
                if (orders != null)
                    return View(orders);
            }
            return NotFound();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DealerCenter/Controllers/SupplierController.cs
using DealerCenter.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DealerCenter.Controllers
{
    public class SupplierController : Controller
    {
        DealerCenterContext db;

        public SupplierController(DealerCenterContext context)
        {
            db = context;
        }
        
        public IActionResult Suppliers()
        {
            IQueryable<Supplier> supplier = db.Suppliers.Include(s => s.Machineries);
            return View(supplier.ToList());
        }

        [Authorize(Roles = "Администратор, ОтветственныйЗаЗакупку")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Supplier supplier)
        {
            db.Suppliers.Add(supplier);
            await db.SaveChangesAsync();
            return RedirectToAction("Suppliers");
        }

        [Authorize(Roles = "Администратор, ОтветственныйЗаЗакупку")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Supplier supplier = await db.Suppliers.FirstOrDefaultAsync(p => p.Id == id);
                if (supplier != null)
                {
                    return View(supplier);
                }
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Supplier supplier)
        {
            db.Suppliers.Update(supplier);
            await db.SaveChangesAsync();
            return RedirectToAction("Suppliers");
        }


        [Authorize(Roles = "Администратор, ОтветственныйЗаЗакупку")]
        [HttpGet]
        [ActionName("FlagDelete")]
        public async Task<IActionResult> ConfirmFlagDelete(int? id)
        {
            if (id != null)
            {
                Supplier supplier = await db.Suppliers.FirstOrDefaultAsync(p => p.Id == id);
                if (supplier != null)
                    return View(supplier);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> FlagDelete(int? id)
        {
            if (id != null)
            {
                Supplier supplier = await db.Suppliers.Include(s => s.Machineries).FirstOrDefaultAsync(p => p.Id == id);
                if (supplier != null)
                {
                    supplier.isDeleted = true;
                    db.Suppliers.Update(supplier);
                    await db.SaveChangesAsync();
                    foreach(var machinery in supplier.Machineries)
                    {
                        machinery.isDeleted = true;
                        await db.SaveChangesAsync();
                    }
                    return RedirectToAction("Suppliers");
                }
            }
            return NotFound();
        }

        [Authorize(Roles = "Администратор, ОтветственныйЗаЗакупку")]
        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Supplier supplier = await db.Suppliers.FirstOrDefaultAsync(p => p.Id == id);
                if (supplier != null)
                    return View(supplier);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                Supplier suppliers = await db.Suppliers.FirstOrDefaultAsync(p => p.Id == id);
                if (suppliers != null)
                {
                    db.Suppliers.Remove(suppliers);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Suppliers");
                }
            }
            return NotFound();
        }

        [Authorize(Roles = "Администратор, ОтветственныйЗаЗакупку")]
        [HttpGet]
        [ActionName("Restore")]
        public async Task<IActionResult> ConfirmRestore(int? id)
        {
            if (id != null)
            {
                Supplier supplier = await db.Suppliers.FirstOrDefaultAsync(p => p.Id == id);
                if (supplier != null)
                    return View(supplier);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Restore(int? id)
        {
            if (id != null)
            {
                Supplier supplier = await db.Suppliers.FirstOrDefaultAsync(p => p.Id == id);
                if (supplier != null)
                {
                    supplier.isDeleted = false;
                    db.Suppliers.Update(supplier);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Suppliers");
                }
            }
            return NotFound();
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id != null)
            {
                List<Machinery> machineries = await db.Machineries.Include(m => m.Supplier)
                                                                  .Include(m => m.MachineryClass)
                                                                  .Where(m => m.SupplierId == id)
                                                                  .ToListAsync();
                if (machineries != null)
                    return View(machineries);
            }
            return NotFound();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DealerCenter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ООО "ГрандТех"</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Account" asp-action="Login"><small>ООО "ГрандТех"</small></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole(RoleEnum.Администратор.ToString()))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Employees"><small>Сотрудники</small></a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="SalesManagerOrder" asp-action="SalesManagerOrders"><small>Оформление/выдача заказов</small></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PurchaseManagerOrder" asp-action="PurchaseManagerOrders"><small>Закупка спецтехники</small></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Clients"><small>Клиенты</small></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Machinery" asp-action="Machineries"><small>Ассортимент спецтехники</small></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Supplier" asp-action="Suppliers"><small>Поставщики</small></a>
                            </li>
                        }
                    </ul>
                </div>
                <div class="collapse navbar-collapse justify-content-end">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout"><small>Выход</small></a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ООО "ГрандТех"
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>